### ISSUE TITLE
GATK3 haplotype caller

### ISSUE THREAD

**Issue by gevro** [gatk-workflows/five-dollar-genome-analysis-pipeline#27]
Hi,
Why is this pipeline still using GATK3 by default for haplotype caller?

"Boolean use_gatk3_haplotype_caller = true"

GATK4 has been out for a while. Either GATK4 is reliable or it isn't, so it seems odd to keep using GATK3 for haplotype caller in the official Broad workflows without an explanation for this. There is no documentation to explain why this is being done.

Thanks.

**Comment by vdauwera** [comment]
Hi @gevro, sorry for the lag, we don't monitor the issues in this repository. GATK4 is definitely reliable and I would encourage you to use it for any new work. However, our production pipeline is very slow to take in updates, because upgrading it triggers the reprocessing of some very large datasets internally, so we don't do it unless it's really necessary.
